version: '2'
services:
    sgcap-app:
        image: sgcap
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sgcap-mysql:3306/sgcap?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sgcap-mysql:
        extends:
            file: mysql.yml
            service: sgcap-mysql
